/*
 * bnm
 * Books N More's API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: samarthr1@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package in.co.booksnmore.api.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AdminEditBookByIdBody
 */
public class AdminEditBookByIdBodyTest {
    private final AdminEditBookByIdBody model = new AdminEditBookByIdBody();

    /**
     * Model tests for AdminEditBookByIdBody
     */
    @Test
    public void testAdminEditBookByIdBody() {
        // TODO: test AdminEditBookByIdBody
    }

    /**
     * Test the property 'ISBN'
     */
    @Test
    public void ISBNTest() {
        // TODO: test ISBN
    }

    /**
     * Test the property 'author'
     */
    @Test
    public void authorTest() {
        // TODO: test author
    }

    /**
     * Test the property 'bookId'
     */
    @Test
    public void bookIdTest() {
        // TODO: test bookId
    }

    /**
     * Test the property 'shelfCode'
     */
    @Test
    public void shelfCodeTest() {
        // TODO: test shelfCode
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'authKey'
     */
    @Test
    public void authKeyTest() {
        // TODO: test authKey
    }

}
