/*
 * bnm
 * Books N More's API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: samarthr1@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package in.co.booksnmore.api.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BookData
 */
public class BookDataTest {
    private final BookData model = new BookData();

    /**
     * Model tests for BookData
     */
    @Test
    public void testBookData() {
        // TODO: test BookData
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'author'
     */
    @Test
    public void authorTest() {
        // TODO: test author
    }

    /**
     * Test the property 'borrowedOn'
     */
    @Test
    public void borrowedOnTest() {
        // TODO: test borrowedOn
    }

    /**
     * Test the property 'canCancel'
     */
    @Test
    public void canCancelTest() {
        // TODO: test canCancel
    }

    /**
     * Test the property 'shelfCode'
     */
    @Test
    public void shelfCodeTest() {
        // TODO: test shelfCode
    }

    /**
     * Test the property 'borrowerId'
     */
    @Test
    public void borrowerIdTest() {
        // TODO: test borrowerId
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
