/*
 * bnm
 * Books N More's API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: samarthr1@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package in.co.booksnmore.api.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import in.co.booksnmore.api.model.CreateMemberInputAddress;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CreateMemberInput
 */
public class CreateMemberInputTest {
    private final CreateMemberInput model = new CreateMemberInput();

    /**
     * Model tests for CreateMemberInput
     */
    @Test
    public void testCreateMemberInput() {
        // TODO: test CreateMemberInput
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'phone'
     */
    @Test
    public void phoneTest() {
        // TODO: test phone
    }

    /**
     * Test the property 'password'
     */
    @Test
    public void passwordTest() {
        // TODO: test password
    }

    /**
     * Test the property 'planType'
     */
    @Test
    public void planTypeTest() {
        // TODO: test planType
    }

    /**
     * Test the property 'authKey'
     */
    @Test
    public void authKeyTest() {
        // TODO: test authKey
    }

    /**
     * Test the property 'confirmPassword'
     */
    @Test
    public void confirmPasswordTest() {
        // TODO: test confirmPassword
    }

}
