/*
 * bnm
 * Books N More's API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: samarthr1@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package in.co.booksnmore.api.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import in.co.booksnmore.api.model.PlanInfoItem;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PlanInfo
 */
public class PlanInfoTest {
    private final PlanInfo model = new PlanInfo();

    /**
     * Model tests for PlanInfo
     */
    @Test
    public void testPlanInfo() {
        // TODO: test PlanInfo
    }

    /**
     * Test the property 'deposit'
     */
    @Test
    public void depositTest() {
        // TODO: test deposit
    }

    /**
     * Test the property 'errorCode'
     */
    @Test
    public void errorCodeTest() {
        // TODO: test errorCode
    }

    /**
     * Test the property 'joiningFee'
     */
    @Test
    public void joiningFeeTest() {
        // TODO: test joiningFee
    }

    /**
     * Test the property 'plans'
     */
    @Test
    public void plansTest() {
        // TODO: test plans
    }

}
