/*
 * bnm
 * Books N More's API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: samarthr1@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package in.co.booksnmore.api.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PlanData
 */
public class PlanDataTest {
    private final PlanData model = new PlanData();

    /**
     * Model tests for PlanData
     */
    @Test
    public void testPlanData() {
        // TODO: test PlanData
    }

    /**
     * Test the property 'duration'
     */
    @Test
    public void durationTest() {
        // TODO: test duration
    }

    /**
     * Test the property 'nextRenewal'
     */
    @Test
    public void nextRenewalTest() {
        // TODO: test nextRenewal
    }

    /**
     * Test the property 'planId'
     */
    @Test
    public void planIdTest() {
        // TODO: test planId
    }

    /**
     * Test the property 'canDelete'
     */
    @Test
    public void canDeleteTest() {
        // TODO: test canDelete
    }

    /**
     * Test the property 'balanceDue'
     */
    @Test
    public void balanceDueTest() {
        // TODO: test balanceDue
    }

}
