/*
 * bnm
 * Books N More's API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: samarthr1@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package in.co.booksnmore.api.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PlanInfoItem
 */
public class PlanInfoItemTest {
    private final PlanInfoItem model = new PlanInfoItem();

    /**
     * Model tests for PlanInfoItem
     */
    @Test
    public void testPlanInfoItem() {
        // TODO: test PlanInfoItem
    }

    /**
     * Test the property 'cost'
     */
    @Test
    public void costTest() {
        // TODO: test cost
    }

    /**
     * Test the property 'duration'
     */
    @Test
    public void durationTest() {
        // TODO: test duration
    }

    /**
     * Test the property 'numDeliveries'
     */
    @Test
    public void numDeliveriesTest() {
        // TODO: test numDeliveries
    }

    /**
     * Test the property 'planType'
     */
    @Test
    public void planTypeTest() {
        // TODO: test planType
    }

}
