/*
 * bnm
 * Books N More's API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: samarthr1@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package in.co.booksnmore.api.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import in.co.booksnmore.api.model.BookData;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SearchData
 */
public class SearchDataTest {
    private final SearchData model = new SearchData();

    /**
     * Model tests for SearchData
     */
    @Test
    public void testSearchData() {
        // TODO: test SearchData
    }

    /**
     * Test the property 'startBook'
     */
    @Test
    public void startBookTest() {
        // TODO: test startBook
    }

    /**
     * Test the property 'booksMatched'
     */
    @Test
    public void booksMatchedTest() {
        // TODO: test booksMatched
    }

    /**
     * Test the property 'endBook'
     */
    @Test
    public void endBookTest() {
        // TODO: test endBook
    }

    /**
     * Test the property 'errorCode'
     */
    @Test
    public void errorCodeTest() {
        // TODO: test errorCode
    }

    /**
     * Test the property 'books'
     */
    @Test
    public void booksTest() {
        // TODO: test books
    }

    /**
     * Test the property 'borrowStatus'
     */
    @Test
    public void borrowStatusTest() {
        // TODO: test borrowStatus
    }

}
