/*
 * bnm
 * Books N More's API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: samarthr1@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package in.co.booksnmore.api.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SubstituteBookData
 */
public class SubstituteBookDataTest {
    private final SubstituteBookData model = new SubstituteBookData();

    /**
     * Model tests for SubstituteBookData
     */
    @Test
    public void testSubstituteBookData() {
        // TODO: test SubstituteBookData
    }

    /**
     * Test the property 'authKey'
     */
    @Test
    public void authKeyTest() {
        // TODO: test authKey
    }

    /**
     * Test the property 'bookId'
     */
    @Test
    public void bookIdTest() {
        // TODO: test bookId
    }

    /**
     * Test the property 'newBookId'
     */
    @Test
    public void newBookIdTest() {
        // TODO: test newBookId
    }

}
