/*
 * bnm
 * Books N More's API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: samarthr1@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package in.co.booksnmore.api.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import in.co.booksnmore.api.model.UserInfoAddress;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for UserInfo
 */
public class UserInfoTest {
    private final UserInfo model = new UserInfo();

    /**
     * Model tests for UserInfo
     */
    @Test
    public void testUserInfo() {
        // TODO: test UserInfo
    }

    /**
     * Test the property 'userType'
     */
    @Test
    public void userTypeTest() {
        // TODO: test userType
    }

    /**
     * Test the property 'numDeliveries'
     */
    @Test
    public void numDeliveriesTest() {
        // TODO: test numDeliveries
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'sex'
     */
    @Test
    public void sexTest() {
        // TODO: test sex
    }

    /**
     * Test the property 'phone'
     */
    @Test
    public void phoneTest() {
        // TODO: test phone
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'borrowStatus'
     */
    @Test
    public void borrowStatusTest() {
        // TODO: test borrowStatus
    }

}
