/*
 * bnm
 * Books N More's API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: samarthr1@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package in.co.booksnmore.api.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for UserInfoAddress
 */
public class UserInfoAddressTest {
    private final UserInfoAddress model = new UserInfoAddress();

    /**
     * Model tests for UserInfoAddress
     */
    @Test
    public void testUserInfoAddress() {
        // TODO: test UserInfoAddress
    }

    /**
     * Test the property 'l1'
     */
    @Test
    public void l1Test() {
        // TODO: test l1
    }

    /**
     * Test the property 'l2'
     */
    @Test
    public void l2Test() {
        // TODO: test l2
    }

    /**
     * Test the property 'pincode'
     */
    @Test
    public void pincodeTest() {
        // TODO: test pincode
    }

    /**
     * Test the property 'city'
     */
    @Test
    public void cityTest() {
        // TODO: test city
    }

}
