/*
 * bnm
 * Books N More's API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: samarthr1@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package in.co.booksnmore.api.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import in.co.booksnmore.api.model.BookData;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for UserBooks
 */
public class UserBooksTest {
    private final UserBooks model = new UserBooks();

    /**
     * Model tests for UserBooks
     */
    @Test
    public void testUserBooks() {
        // TODO: test UserBooks
    }

    /**
     * Test the property 'borrowed'
     */
    @Test
    public void borrowedTest() {
        // TODO: test borrowed
    }

    /**
     * Test the property 'reserved'
     */
    @Test
    public void reservedTest() {
        // TODO: test reserved
    }

    /**
     * Test the property 'readyToReturn'
     */
    @Test
    public void readyToReturnTest() {
        // TODO: test readyToReturn
    }

}
