/*
 * bnm
 * Books N More's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: samarthr1@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package in.co.booksnmore.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import android.os.Parcelable;
import android.os.Parcel;
/**
 * Address
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-09-02T02:43:51.720Z[GMT]")
public class Address implements Parcelable {
  @SerializedName("l1")
  private String l1 = null;

  @SerializedName("l2")
  private String l2 = null;

  @SerializedName("city")
  private String city = null;

  @SerializedName("pincode")
  private String pincode = null;

  public Address() {
  }
  public Address l1(String l1) {
    this.l1 = l1;
    return this;
  }

   /**
   * Get l1
   * @return l1
  **/
  @Schema(required = true, description = "")
  public String getL1() {
    return l1;
  }

  public void setL1(String l1) {
    this.l1 = l1;
  }

  public Address l2(String l2) {
    this.l2 = l2;
    return this;
  }

   /**
   * Get l2
   * @return l2
  **/
  @Schema(description = "")
  public String getL2() {
    return l2;
  }

  public void setL2(String l2) {
    this.l2 = l2;
  }

  public Address city(String city) {
    this.city = city;
    return this;
  }

   /**
   * Get city
   * @return city
  **/
  @Schema(required = true, description = "")
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public Address pincode(String pincode) {
    this.pincode = pincode;
    return this;
  }

   /**
   * Get pincode
   * @return pincode
  **/
  @Schema(required = true, description = "")
  public String getPincode() {
    return pincode;
  }

  public void setPincode(String pincode) {
    this.pincode = pincode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Address address = (Address) o;
    return Objects.equals(this.l1, address.l1) &&
        Objects.equals(this.l2, address.l2) &&
        Objects.equals(this.city, address.city) &&
        Objects.equals(this.pincode, address.pincode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(l1, l2, city, pincode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Address {\n");
    
    sb.append("    l1: ").append(toIndentedString(l1)).append("\n");
    sb.append("    l2: ").append(toIndentedString(l2)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    pincode: ").append(toIndentedString(pincode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public void writeToParcel(Parcel out, int flags) {
    out.writeValue(l1);
    out.writeValue(l2);
    out.writeValue(city);
    out.writeValue(pincode);
  }

  Address(Parcel in) {
    l1 = (String)in.readValue(null);
    l2 = (String)in.readValue(null);
    city = (String)in.readValue(null);
    pincode = (String)in.readValue(null);
  }

  public int describeContents() {
    return 0;
  }

  public static final Parcelable.Creator<Address> CREATOR = new Parcelable.Creator<Address>() {
    public Address createFromParcel(Parcel in) {
      return new Address(in);
    }
    public Address[] newArray(int size) {
      return new Address[size];
    }
  };
}
