/*
 * bnm
 * Books N More's API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: samarthr1@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package in.co.booksnmore.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import android.os.Parcelable;
import android.os.Parcel;

/**
 * AdminBookByIdData
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-07-27T18:09:10.466+05:30[Asia/Kolkata]")
public class AdminBookByIdData implements Parcelable {
  public static final String SERIALIZED_NAME_I_S_B_N = "ISBN";
  @SerializedName(SERIALIZED_NAME_I_S_B_N)
  private String ISBN;

  public static final String SERIALIZED_NAME_AUTHOR = "author";
  @SerializedName(SERIALIZED_NAME_AUTHOR)
  private String author;

  public static final String SERIALIZED_NAME_ERROR_CODE = "errorCode";
  @SerializedName(SERIALIZED_NAME_ERROR_CODE)
  private BigDecimal errorCode;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private BigDecimal id;

  public static final String SERIALIZED_NAME_SHELF_CODE = "shelfCode";
  @SerializedName(SERIALIZED_NAME_SHELF_CODE)
  private String shelfCode;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  private String title;

  public AdminBookByIdData() {
  }

  public AdminBookByIdData ISBN(String ISBN) {
    
    this.ISBN = ISBN;
    return this;
  }

   /**
   * Get ISBN
   * @return ISBN
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getISBN() {
    return ISBN;
  }


  public void setISBN(String ISBN) {
    this.ISBN = ISBN;
  }


  public AdminBookByIdData author(String author) {
    
    this.author = author;
    return this;
  }

   /**
   * Get author
   * @return author
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAuthor() {
    return author;
  }


  public void setAuthor(String author) {
    this.author = author;
  }


  public AdminBookByIdData errorCode(BigDecimal errorCode) {
    
    this.errorCode = errorCode;
    return this;
  }

   /**
   * Get errorCode
   * @return errorCode
  **/
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getErrorCode() {
    return errorCode;
  }


  public void setErrorCode(BigDecimal errorCode) {
    this.errorCode = errorCode;
  }


  public AdminBookByIdData id(BigDecimal id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getId() {
    return id;
  }


  public void setId(BigDecimal id) {
    this.id = id;
  }


  public AdminBookByIdData shelfCode(String shelfCode) {
    
    this.shelfCode = shelfCode;
    return this;
  }

   /**
   * Get shelfCode
   * @return shelfCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getShelfCode() {
    return shelfCode;
  }


  public void setShelfCode(String shelfCode) {
    this.shelfCode = shelfCode;
  }


  public AdminBookByIdData title(String title) {
    
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTitle() {
    return title;
  }


  public void setTitle(String title) {
    this.title = title;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdminBookByIdData adminBookByIdData = (AdminBookByIdData) o;
    return Objects.equals(this.ISBN, adminBookByIdData.ISBN) &&
        Objects.equals(this.author, adminBookByIdData.author) &&
        Objects.equals(this.errorCode, adminBookByIdData.errorCode) &&
        Objects.equals(this.id, adminBookByIdData.id) &&
        Objects.equals(this.shelfCode, adminBookByIdData.shelfCode) &&
        Objects.equals(this.title, adminBookByIdData.title);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ISBN, author, errorCode, id, shelfCode, title);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdminBookByIdData {\n");
    sb.append("    ISBN: ").append(toIndentedString(ISBN)).append("\n");
    sb.append("    author: ").append(toIndentedString(author)).append("\n");
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    shelfCode: ").append(toIndentedString(shelfCode)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public void writeToParcel(Parcel out, int flags) {
    out.writeValue(ISBN);
    out.writeValue(author);
    out.writeValue(errorCode);
    out.writeValue(id);
    out.writeValue(shelfCode);
    out.writeValue(title);
  }

  AdminBookByIdData(Parcel in) {
    ISBN = (String)in.readValue(null);
    author = (String)in.readValue(null);
    errorCode = (BigDecimal)in.readValue(BigDecimal.class.getClassLoader());
    id = (BigDecimal)in.readValue(BigDecimal.class.getClassLoader());
    shelfCode = (String)in.readValue(null);
    title = (String)in.readValue(null);
  }

  public int describeContents() {
    return 0;
  }

  public static final Parcelable.Creator<AdminBookByIdData> CREATOR = new Parcelable.Creator<AdminBookByIdData>() {
    public AdminBookByIdData createFromParcel(Parcel in) {
      return new AdminBookByIdData(in);
    }
    public AdminBookByIdData[] newArray(int size) {
      return new AdminBookByIdData[size];
    }
  };
}

