/*
 * bnm
 * Books N More's API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: samarthr1@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package in.co.booksnmore.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import android.os.Parcelable;
import android.os.Parcel;

/**
 * AdminEditBookByIdBody
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-07-27T18:09:10.466+05:30[Asia/Kolkata]")
public class AdminEditBookByIdBody implements Parcelable {
  public static final String SERIALIZED_NAME_I_S_B_N = "ISBN";
  @SerializedName(SERIALIZED_NAME_I_S_B_N)
  private String ISBN;

  public static final String SERIALIZED_NAME_AUTHOR = "author";
  @SerializedName(SERIALIZED_NAME_AUTHOR)
  private String author;

  public static final String SERIALIZED_NAME_BOOK_ID = "bookId";
  @SerializedName(SERIALIZED_NAME_BOOK_ID)
  private BigDecimal bookId;

  public static final String SERIALIZED_NAME_SHELF_CODE = "shelfCode";
  @SerializedName(SERIALIZED_NAME_SHELF_CODE)
  private String shelfCode;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  private String title;

  public static final String SERIALIZED_NAME_AUTH_KEY = "authKey";
  @SerializedName(SERIALIZED_NAME_AUTH_KEY)
  private String authKey;

  public AdminEditBookByIdBody() {
  }

  public AdminEditBookByIdBody ISBN(String ISBN) {
    
    this.ISBN = ISBN;
    return this;
  }

   /**
   * Get ISBN
   * @return ISBN
  **/
  @ApiModelProperty(required = true, value = "")

  public String getISBN() {
    return ISBN;
  }


  public void setISBN(String ISBN) {
    this.ISBN = ISBN;
  }


  public AdminEditBookByIdBody author(String author) {
    
    this.author = author;
    return this;
  }

   /**
   * Get author
   * @return author
  **/
  @ApiModelProperty(required = true, value = "")

  public String getAuthor() {
    return author;
  }


  public void setAuthor(String author) {
    this.author = author;
  }


  public AdminEditBookByIdBody bookId(BigDecimal bookId) {
    
    this.bookId = bookId;
    return this;
  }

   /**
   * Get bookId
   * @return bookId
  **/
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getBookId() {
    return bookId;
  }


  public void setBookId(BigDecimal bookId) {
    this.bookId = bookId;
  }


  public AdminEditBookByIdBody shelfCode(String shelfCode) {
    
    this.shelfCode = shelfCode;
    return this;
  }

   /**
   * Get shelfCode
   * @return shelfCode
  **/
  @ApiModelProperty(required = true, value = "")

  public String getShelfCode() {
    return shelfCode;
  }


  public void setShelfCode(String shelfCode) {
    this.shelfCode = shelfCode;
  }


  public AdminEditBookByIdBody title(String title) {
    
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @ApiModelProperty(required = true, value = "")

  public String getTitle() {
    return title;
  }


  public void setTitle(String title) {
    this.title = title;
  }


  public AdminEditBookByIdBody authKey(String authKey) {
    
    this.authKey = authKey;
    return this;
  }

   /**
   * Get authKey
   * @return authKey
  **/
  @ApiModelProperty(required = true, value = "")

  public String getAuthKey() {
    return authKey;
  }


  public void setAuthKey(String authKey) {
    this.authKey = authKey;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdminEditBookByIdBody adminEditBookByIdBody = (AdminEditBookByIdBody) o;
    return Objects.equals(this.ISBN, adminEditBookByIdBody.ISBN) &&
        Objects.equals(this.author, adminEditBookByIdBody.author) &&
        Objects.equals(this.bookId, adminEditBookByIdBody.bookId) &&
        Objects.equals(this.shelfCode, adminEditBookByIdBody.shelfCode) &&
        Objects.equals(this.title, adminEditBookByIdBody.title) &&
        Objects.equals(this.authKey, adminEditBookByIdBody.authKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ISBN, author, bookId, shelfCode, title, authKey);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdminEditBookByIdBody {\n");
    sb.append("    ISBN: ").append(toIndentedString(ISBN)).append("\n");
    sb.append("    author: ").append(toIndentedString(author)).append("\n");
    sb.append("    bookId: ").append(toIndentedString(bookId)).append("\n");
    sb.append("    shelfCode: ").append(toIndentedString(shelfCode)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    authKey: ").append(toIndentedString(authKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public void writeToParcel(Parcel out, int flags) {
    out.writeValue(ISBN);
    out.writeValue(author);
    out.writeValue(bookId);
    out.writeValue(shelfCode);
    out.writeValue(title);
    out.writeValue(authKey);
  }

  AdminEditBookByIdBody(Parcel in) {
    ISBN = (String)in.readValue(null);
    author = (String)in.readValue(null);
    bookId = (BigDecimal)in.readValue(BigDecimal.class.getClassLoader());
    shelfCode = (String)in.readValue(null);
    title = (String)in.readValue(null);
    authKey = (String)in.readValue(null);
  }

  public int describeContents() {
    return 0;
  }

  public static final Parcelable.Creator<AdminEditBookByIdBody> CREATOR = new Parcelable.Creator<AdminEditBookByIdBody>() {
    public AdminEditBookByIdBody createFromParcel(Parcel in) {
      return new AdminEditBookByIdBody(in);
    }
    public AdminEditBookByIdBody[] newArray(int size) {
      return new AdminEditBookByIdBody[size];
    }
  };
}

