/*
 * bnm
 * Books N More's API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: samarthr1@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package in.co.booksnmore.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import android.os.Parcelable;
import android.os.Parcel;

/**
 * AdminActionInput
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-07-27T18:09:10.466+05:30[Asia/Kolkata]")
public class AdminActionInput implements Parcelable {
  public static final String SERIALIZED_NAME_AUTH_KEY = "authKey";
  @SerializedName(SERIALIZED_NAME_AUTH_KEY)
  private String authKey;

  public static final String SERIALIZED_NAME_BOOK_ID = "bookId";
  @SerializedName(SERIALIZED_NAME_BOOK_ID)
  private String bookId;

  public static final String SERIALIZED_NAME_MEMBER_ID = "memberId";
  @SerializedName(SERIALIZED_NAME_MEMBER_ID)
  private String memberId;

  public AdminActionInput() {
  }

  public AdminActionInput authKey(String authKey) {
    
    this.authKey = authKey;
    return this;
  }

   /**
   * Get authKey
   * @return authKey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAuthKey() {
    return authKey;
  }


  public void setAuthKey(String authKey) {
    this.authKey = authKey;
  }


  public AdminActionInput bookId(String bookId) {
    
    this.bookId = bookId;
    return this;
  }

   /**
   * Get bookId
   * @return bookId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getBookId() {
    return bookId;
  }


  public void setBookId(String bookId) {
    this.bookId = bookId;
  }


  public AdminActionInput memberId(String memberId) {
    
    this.memberId = memberId;
    return this;
  }

   /**
   * Get memberId
   * @return memberId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getMemberId() {
    return memberId;
  }


  public void setMemberId(String memberId) {
    this.memberId = memberId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdminActionInput adminActionInput = (AdminActionInput) o;
    return Objects.equals(this.authKey, adminActionInput.authKey) &&
        Objects.equals(this.bookId, adminActionInput.bookId) &&
        Objects.equals(this.memberId, adminActionInput.memberId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authKey, bookId, memberId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdminActionInput {\n");
    sb.append("    authKey: ").append(toIndentedString(authKey)).append("\n");
    sb.append("    bookId: ").append(toIndentedString(bookId)).append("\n");
    sb.append("    memberId: ").append(toIndentedString(memberId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public void writeToParcel(Parcel out, int flags) {
    out.writeValue(authKey);
    out.writeValue(bookId);
    out.writeValue(memberId);
  }

  AdminActionInput(Parcel in) {
    authKey = (String)in.readValue(null);
    bookId = (String)in.readValue(null);
    memberId = (String)in.readValue(null);
  }

  public int describeContents() {
    return 0;
  }

  public static final Parcelable.Creator<AdminActionInput> CREATOR = new Parcelable.Creator<AdminActionInput>() {
    public AdminActionInput createFromParcel(Parcel in) {
      return new AdminActionInput(in);
    }
    public AdminActionInput[] newArray(int size) {
      return new AdminActionInput[size];
    }
  };
}

