/*
 * bnm
 * Books N More's API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: samarthr1@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package in.co.booksnmore.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import android.os.Parcelable;
import android.os.Parcel;

/**
 * BookData
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-07-27T18:09:10.466+05:30[Asia/Kolkata]")
public class BookData implements Parcelable {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private BigDecimal id;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  private String title;

  public static final String SERIALIZED_NAME_AUTHOR = "author";
  @SerializedName(SERIALIZED_NAME_AUTHOR)
  private String author;

  public static final String SERIALIZED_NAME_BORROWED_ON = "borrowedOn";
  @SerializedName(SERIALIZED_NAME_BORROWED_ON)
  private BigDecimal borrowedOn;

  public static final String SERIALIZED_NAME_CAN_CANCEL = "canCancel";
  @SerializedName(SERIALIZED_NAME_CAN_CANCEL)
  private Boolean canCancel;

  public static final String SERIALIZED_NAME_SHELF_CODE = "shelfCode";
  @SerializedName(SERIALIZED_NAME_SHELF_CODE)
  private String shelfCode;

  public static final String SERIALIZED_NAME_BORROWER_ID = "borrowerId";
  @SerializedName(SERIALIZED_NAME_BORROWER_ID)
  private BigDecimal borrowerId;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private BigDecimal status;

  public BookData() {
  }

  public BookData id(BigDecimal id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getId() {
    return id;
  }


  public void setId(BigDecimal id) {
    this.id = id;
  }


  public BookData title(String title) {
    
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @ApiModelProperty(required = true, value = "")

  public String getTitle() {
    return title;
  }


  public void setTitle(String title) {
    this.title = title;
  }


  public BookData author(String author) {
    
    this.author = author;
    return this;
  }

   /**
   * Get author
   * @return author
  **/
  @ApiModelProperty(required = true, value = "")

  public String getAuthor() {
    return author;
  }


  public void setAuthor(String author) {
    this.author = author;
  }


  public BookData borrowedOn(BigDecimal borrowedOn) {
    
    this.borrowedOn = borrowedOn;
    return this;
  }

   /**
   * Get borrowedOn
   * @return borrowedOn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getBorrowedOn() {
    return borrowedOn;
  }


  public void setBorrowedOn(BigDecimal borrowedOn) {
    this.borrowedOn = borrowedOn;
  }


  public BookData canCancel(Boolean canCancel) {
    
    this.canCancel = canCancel;
    return this;
  }

   /**
   * Get canCancel
   * @return canCancel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getCanCancel() {
    return canCancel;
  }


  public void setCanCancel(Boolean canCancel) {
    this.canCancel = canCancel;
  }


  public BookData shelfCode(String shelfCode) {
    
    this.shelfCode = shelfCode;
    return this;
  }

   /**
   * Get shelfCode
   * @return shelfCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getShelfCode() {
    return shelfCode;
  }


  public void setShelfCode(String shelfCode) {
    this.shelfCode = shelfCode;
  }


  public BookData borrowerId(BigDecimal borrowerId) {
    
    this.borrowerId = borrowerId;
    return this;
  }

   /**
   * Get borrowerId
   * @return borrowerId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getBorrowerId() {
    return borrowerId;
  }


  public void setBorrowerId(BigDecimal borrowerId) {
    this.borrowerId = borrowerId;
  }


  public BookData status(BigDecimal status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getStatus() {
    return status;
  }


  public void setStatus(BigDecimal status) {
    this.status = status;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BookData bookData = (BookData) o;
    return Objects.equals(this.id, bookData.id) &&
        Objects.equals(this.title, bookData.title) &&
        Objects.equals(this.author, bookData.author) &&
        Objects.equals(this.borrowedOn, bookData.borrowedOn) &&
        Objects.equals(this.canCancel, bookData.canCancel) &&
        Objects.equals(this.shelfCode, bookData.shelfCode) &&
        Objects.equals(this.borrowerId, bookData.borrowerId) &&
        Objects.equals(this.status, bookData.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, title, author, borrowedOn, canCancel, shelfCode, borrowerId, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BookData {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    author: ").append(toIndentedString(author)).append("\n");
    sb.append("    borrowedOn: ").append(toIndentedString(borrowedOn)).append("\n");
    sb.append("    canCancel: ").append(toIndentedString(canCancel)).append("\n");
    sb.append("    shelfCode: ").append(toIndentedString(shelfCode)).append("\n");
    sb.append("    borrowerId: ").append(toIndentedString(borrowerId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public void writeToParcel(Parcel out, int flags) {
    out.writeValue(id);
    out.writeValue(title);
    out.writeValue(author);
    out.writeValue(borrowedOn);
    out.writeValue(canCancel);
    out.writeValue(shelfCode);
    out.writeValue(borrowerId);
    out.writeValue(status);
  }

  BookData(Parcel in) {
    id = (BigDecimal)in.readValue(BigDecimal.class.getClassLoader());
    title = (String)in.readValue(null);
    author = (String)in.readValue(null);
    borrowedOn = (BigDecimal)in.readValue(BigDecimal.class.getClassLoader());
    canCancel = (Boolean)in.readValue(null);
    shelfCode = (String)in.readValue(null);
    borrowerId = (BigDecimal)in.readValue(BigDecimal.class.getClassLoader());
    status = (BigDecimal)in.readValue(BigDecimal.class.getClassLoader());
  }

  public int describeContents() {
    return 0;
  }

  public static final Parcelable.Creator<BookData> CREATOR = new Parcelable.Creator<BookData>() {
    public BookData createFromParcel(Parcel in) {
      return new BookData(in);
    }
    public BookData[] newArray(int size) {
      return new BookData[size];
    }
  };
}

