/*
 * bnm
 * Books N More's API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: samarthr1@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package in.co.booksnmore.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import android.os.Parcelable;
import android.os.Parcel;

/**
 * GetAuthKeyRespone
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-07-27T18:09:10.466+05:30[Asia/Kolkata]")
public class GetAuthKeyRespone implements Parcelable {
  public static final String SERIALIZED_NAME_AUTH_KEY = "authKey";
  @SerializedName(SERIALIZED_NAME_AUTH_KEY)
  private String authKey;

  public static final String SERIALIZED_NAME_ERROR_CODE = "errorCode";
  @SerializedName(SERIALIZED_NAME_ERROR_CODE)
  private BigDecimal errorCode;

  public GetAuthKeyRespone() {
  }

  public GetAuthKeyRespone authKey(String authKey) {
    
    this.authKey = authKey;
    return this;
  }

   /**
   * Get authKey
   * @return authKey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAuthKey() {
    return authKey;
  }


  public void setAuthKey(String authKey) {
    this.authKey = authKey;
  }


  public GetAuthKeyRespone errorCode(BigDecimal errorCode) {
    
    this.errorCode = errorCode;
    return this;
  }

   /**
   * Get errorCode
   * @return errorCode
  **/
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getErrorCode() {
    return errorCode;
  }


  public void setErrorCode(BigDecimal errorCode) {
    this.errorCode = errorCode;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetAuthKeyRespone getAuthKeyRespone = (GetAuthKeyRespone) o;
    return Objects.equals(this.authKey, getAuthKeyRespone.authKey) &&
        Objects.equals(this.errorCode, getAuthKeyRespone.errorCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authKey, errorCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetAuthKeyRespone {\n");
    sb.append("    authKey: ").append(toIndentedString(authKey)).append("\n");
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public void writeToParcel(Parcel out, int flags) {
    out.writeValue(authKey);
    out.writeValue(errorCode);
  }

  GetAuthKeyRespone(Parcel in) {
    authKey = (String)in.readValue(null);
    errorCode = (BigDecimal)in.readValue(BigDecimal.class.getClassLoader());
  }

  public int describeContents() {
    return 0;
  }

  public static final Parcelable.Creator<GetAuthKeyRespone> CREATOR = new Parcelable.Creator<GetAuthKeyRespone>() {
    public GetAuthKeyRespone createFromParcel(Parcel in) {
      return new GetAuthKeyRespone(in);
    }
    public GetAuthKeyRespone[] newArray(int size) {
      return new GetAuthKeyRespone[size];
    }
  };
}

