/*
 * bnm
 * Books N More's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: samarthr1@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package in.co.booksnmore.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import in.co.booksnmore.api.model.HotBooks;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import android.os.Parcelable;
import android.os.Parcel;
/**
 * InlineResponse200
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-09-14T04:05:40.533Z[GMT]")
public class InlineResponse200 implements Parcelable {
  @SerializedName("errorCode")
  private BigDecimal errorCode = null;

  @SerializedName("books")
  private List<HotBooks> books = null;

  public InlineResponse200() {
  }
  public InlineResponse200 errorCode(BigDecimal errorCode) {
    this.errorCode = errorCode;
    return this;
  }

   /**
   * Get errorCode
   * @return errorCode
  **/
  @Schema(required = true, description = "")
  public BigDecimal getErrorCode() {
    return errorCode;
  }

  public void setErrorCode(BigDecimal errorCode) {
    this.errorCode = errorCode;
  }

  public InlineResponse200 books(List<HotBooks> books) {
    this.books = books;
    return this;
  }

  public InlineResponse200 addBooksItem(HotBooks booksItem) {
    if (this.books == null) {
      this.books = new ArrayList<HotBooks>();
    }
    this.books.add(booksItem);
    return this;
  }

   /**
   * Get books
   * @return books
  **/
  @Schema(description = "")
  public List<HotBooks> getBooks() {
    return books;
  }

  public void setBooks(List<HotBooks> books) {
    this.books = books;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse200 inlineResponse200 = (InlineResponse200) o;
    return Objects.equals(this.errorCode, inlineResponse200.errorCode) &&
        Objects.equals(this.books, inlineResponse200.books);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errorCode, books);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse200 {\n");
    
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    books: ").append(toIndentedString(books)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public void writeToParcel(Parcel out, int flags) {
    out.writeValue(errorCode);
    out.writeValue(books);
  }

  InlineResponse200(Parcel in) {
    errorCode = (BigDecimal)in.readValue(BigDecimal.class.getClassLoader());
    books = (List<HotBooks>)in.readValue(HotBooks.class.getClassLoader());
  }

  public int describeContents() {
    return 0;
  }

  public static final Parcelable.Creator<InlineResponse200> CREATOR = new Parcelable.Creator<InlineResponse200>() {
    public InlineResponse200 createFromParcel(Parcel in) {
      return new InlineResponse200(in);
    }
    public InlineResponse200[] newArray(int size) {
      return new InlineResponse200[size];
    }
  };
}
