/*
 * bnm
 * Books N More's API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: samarthr1@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package in.co.booksnmore.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import in.co.booksnmore.api.model.User;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import android.os.Parcelable;
import android.os.Parcel;

/**
 * MemberAction
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-07-27T18:09:10.466+05:30[Asia/Kolkata]")
public class MemberAction implements Parcelable {
  public static final String SERIALIZED_NAME_ERROR_CODE = "errorCode";
  @SerializedName(SERIALIZED_NAME_ERROR_CODE)
  private BigDecimal errorCode;

  public static final String SERIALIZED_NAME_MEMBER_DATA = "memberData";
  @SerializedName(SERIALIZED_NAME_MEMBER_DATA)
  private User memberData;

  public MemberAction() {
  }

  public MemberAction errorCode(BigDecimal errorCode) {
    
    this.errorCode = errorCode;
    return this;
  }

   /**
   * Get errorCode
   * @return errorCode
  **/
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getErrorCode() {
    return errorCode;
  }


  public void setErrorCode(BigDecimal errorCode) {
    this.errorCode = errorCode;
  }


  public MemberAction memberData(User memberData) {
    
    this.memberData = memberData;
    return this;
  }

   /**
   * Get memberData
   * @return memberData
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public User getMemberData() {
    return memberData;
  }


  public void setMemberData(User memberData) {
    this.memberData = memberData;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MemberAction memberAction = (MemberAction) o;
    return Objects.equals(this.errorCode, memberAction.errorCode) &&
        Objects.equals(this.memberData, memberAction.memberData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errorCode, memberData);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MemberAction {\n");
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    memberData: ").append(toIndentedString(memberData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public void writeToParcel(Parcel out, int flags) {
    out.writeValue(errorCode);
    out.writeValue(memberData);
  }

  MemberAction(Parcel in) {
    errorCode = (BigDecimal)in.readValue(BigDecimal.class.getClassLoader());
    memberData = (User)in.readValue(User.class.getClassLoader());
  }

  public int describeContents() {
    return 0;
  }

  public static final Parcelable.Creator<MemberAction> CREATOR = new Parcelable.Creator<MemberAction>() {
    public MemberAction createFromParcel(Parcel in) {
      return new MemberAction(in);
    }
    public MemberAction[] newArray(int size) {
      return new MemberAction[size];
    }
  };
}

