/*
 * bnm
 * Books N More's API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: samarthr1@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package in.co.booksnmore.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import android.os.Parcelable;
import android.os.Parcel;

/**
 * PlanInfoItem
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-07-27T18:09:10.466+05:30[Asia/Kolkata]")
public class PlanInfoItem implements Parcelable {
  public static final String SERIALIZED_NAME_COST = "cost";
  @SerializedName(SERIALIZED_NAME_COST)
  private BigDecimal cost;

  public static final String SERIALIZED_NAME_DURATION = "duration";
  @SerializedName(SERIALIZED_NAME_DURATION)
  private String duration;

  public static final String SERIALIZED_NAME_NUM_DELIVERIES = "numDeliveries";
  @SerializedName(SERIALIZED_NAME_NUM_DELIVERIES)
  private BigDecimal numDeliveries;

  public static final String SERIALIZED_NAME_PLAN_TYPE = "planType";
  @SerializedName(SERIALIZED_NAME_PLAN_TYPE)
  private String planType;

  public PlanInfoItem() {
  }

  public PlanInfoItem cost(BigDecimal cost) {
    
    this.cost = cost;
    return this;
  }

   /**
   * Get cost
   * @return cost
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getCost() {
    return cost;
  }


  public void setCost(BigDecimal cost) {
    this.cost = cost;
  }


  public PlanInfoItem duration(String duration) {
    
    this.duration = duration;
    return this;
  }

   /**
   * Get duration
   * @return duration
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDuration() {
    return duration;
  }


  public void setDuration(String duration) {
    this.duration = duration;
  }


  public PlanInfoItem numDeliveries(BigDecimal numDeliveries) {
    
    this.numDeliveries = numDeliveries;
    return this;
  }

   /**
   * Get numDeliveries
   * @return numDeliveries
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getNumDeliveries() {
    return numDeliveries;
  }


  public void setNumDeliveries(BigDecimal numDeliveries) {
    this.numDeliveries = numDeliveries;
  }


  public PlanInfoItem planType(String planType) {
    
    this.planType = planType;
    return this;
  }

   /**
   * Get planType
   * @return planType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPlanType() {
    return planType;
  }


  public void setPlanType(String planType) {
    this.planType = planType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlanInfoItem planInfoItem = (PlanInfoItem) o;
    return Objects.equals(this.cost, planInfoItem.cost) &&
        Objects.equals(this.duration, planInfoItem.duration) &&
        Objects.equals(this.numDeliveries, planInfoItem.numDeliveries) &&
        Objects.equals(this.planType, planInfoItem.planType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cost, duration, numDeliveries, planType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlanInfoItem {\n");
    sb.append("    cost: ").append(toIndentedString(cost)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    numDeliveries: ").append(toIndentedString(numDeliveries)).append("\n");
    sb.append("    planType: ").append(toIndentedString(planType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public void writeToParcel(Parcel out, int flags) {
    out.writeValue(cost);
    out.writeValue(duration);
    out.writeValue(numDeliveries);
    out.writeValue(planType);
  }

  PlanInfoItem(Parcel in) {
    cost = (BigDecimal)in.readValue(BigDecimal.class.getClassLoader());
    duration = (String)in.readValue(null);
    numDeliveries = (BigDecimal)in.readValue(BigDecimal.class.getClassLoader());
    planType = (String)in.readValue(null);
  }

  public int describeContents() {
    return 0;
  }

  public static final Parcelable.Creator<PlanInfoItem> CREATOR = new Parcelable.Creator<PlanInfoItem>() {
    public PlanInfoItem createFromParcel(Parcel in) {
      return new PlanInfoItem(in);
    }
    public PlanInfoItem[] newArray(int size) {
      return new PlanInfoItem[size];
    }
  };
}

