/*
 * bnm
 * Books N More's API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: samarthr1@outlook.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package in.co.booksnmore.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import android.os.Parcelable;
import android.os.Parcel;

/**
 * PlanData
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-07-27T18:09:10.466+05:30[Asia/Kolkata]")
public class PlanData implements Parcelable {
  public static final String SERIALIZED_NAME_DURATION = "duration";
  @SerializedName(SERIALIZED_NAME_DURATION)
  private String duration;

  public static final String SERIALIZED_NAME_NEXT_RENEWAL = "nextRenewal";
  @SerializedName(SERIALIZED_NAME_NEXT_RENEWAL)
  private BigDecimal nextRenewal;

  public static final String SERIALIZED_NAME_PLAN_ID = "planId";
  @SerializedName(SERIALIZED_NAME_PLAN_ID)
  private BigDecimal planId;

  public static final String SERIALIZED_NAME_CAN_DELETE = "canDelete";
  @SerializedName(SERIALIZED_NAME_CAN_DELETE)
  private String canDelete;

  public static final String SERIALIZED_NAME_BALANCE_DUE = "balanceDue";
  @SerializedName(SERIALIZED_NAME_BALANCE_DUE)
  private BigDecimal balanceDue;

  public PlanData() {
  }

  public PlanData duration(String duration) {
    
    this.duration = duration;
    return this;
  }

   /**
   * Get duration
   * @return duration
  **/
  @ApiModelProperty(required = true, value = "")

  public String getDuration() {
    return duration;
  }


  public void setDuration(String duration) {
    this.duration = duration;
  }


  public PlanData nextRenewal(BigDecimal nextRenewal) {
    
    this.nextRenewal = nextRenewal;
    return this;
  }

   /**
   * Get nextRenewal
   * @return nextRenewal
  **/
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getNextRenewal() {
    return nextRenewal;
  }


  public void setNextRenewal(BigDecimal nextRenewal) {
    this.nextRenewal = nextRenewal;
  }


  public PlanData planId(BigDecimal planId) {
    
    this.planId = planId;
    return this;
  }

   /**
   * Get planId
   * @return planId
  **/
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getPlanId() {
    return planId;
  }


  public void setPlanId(BigDecimal planId) {
    this.planId = planId;
  }


  public PlanData canDelete(String canDelete) {
    
    this.canDelete = canDelete;
    return this;
  }

   /**
   * Get canDelete
   * @return canDelete
  **/
  @ApiModelProperty(required = true, value = "")

  public String getCanDelete() {
    return canDelete;
  }


  public void setCanDelete(String canDelete) {
    this.canDelete = canDelete;
  }


  public PlanData balanceDue(BigDecimal balanceDue) {
    
    this.balanceDue = balanceDue;
    return this;
  }

   /**
   * Get balanceDue
   * @return balanceDue
  **/
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getBalanceDue() {
    return balanceDue;
  }


  public void setBalanceDue(BigDecimal balanceDue) {
    this.balanceDue = balanceDue;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlanData planData = (PlanData) o;
    return Objects.equals(this.duration, planData.duration) &&
        Objects.equals(this.nextRenewal, planData.nextRenewal) &&
        Objects.equals(this.planId, planData.planId) &&
        Objects.equals(this.canDelete, planData.canDelete) &&
        Objects.equals(this.balanceDue, planData.balanceDue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(duration, nextRenewal, planId, canDelete, balanceDue);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlanData {\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    nextRenewal: ").append(toIndentedString(nextRenewal)).append("\n");
    sb.append("    planId: ").append(toIndentedString(planId)).append("\n");
    sb.append("    canDelete: ").append(toIndentedString(canDelete)).append("\n");
    sb.append("    balanceDue: ").append(toIndentedString(balanceDue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public void writeToParcel(Parcel out, int flags) {
    out.writeValue(duration);
    out.writeValue(nextRenewal);
    out.writeValue(planId);
    out.writeValue(canDelete);
    out.writeValue(balanceDue);
  }

  PlanData(Parcel in) {
    duration = (String)in.readValue(null);
    nextRenewal = (BigDecimal)in.readValue(BigDecimal.class.getClassLoader());
    planId = (BigDecimal)in.readValue(BigDecimal.class.getClassLoader());
    canDelete = (String)in.readValue(null);
    balanceDue = (BigDecimal)in.readValue(BigDecimal.class.getClassLoader());
  }

  public int describeContents() {
    return 0;
  }

  public static final Parcelable.Creator<PlanData> CREATOR = new Parcelable.Creator<PlanData>() {
    public PlanData createFromParcel(Parcel in) {
      return new PlanData(in);
    }
    public PlanData[] newArray(int size) {
      return new PlanData[size];
    }
  };
}

