/*
 * bnm
 * Books N More's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: samarthr1@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package in.co.booksnmore.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import in.co.booksnmore.api.model.TransactionReportRow;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import android.os.Parcelable;
import android.os.Parcel;
/**
 * TransactionReport
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-09-01T11:17:49.897Z[GMT]")
public class TransactionReport implements Parcelable {
  @SerializedName("errorCode")
  private Integer errorCode = null;

  @SerializedName("data")
  private List<TransactionReportRow> data = null;

  @SerializedName("totalRecords")
  private Integer totalRecords = null;

  public TransactionReport() {
  }
  public TransactionReport errorCode(Integer errorCode) {
    this.errorCode = errorCode;
    return this;
  }

   /**
   * Get errorCode
   * @return errorCode
  **/
  @Schema(required = true, description = "")
  public Integer getErrorCode() {
    return errorCode;
  }

  public void setErrorCode(Integer errorCode) {
    this.errorCode = errorCode;
  }

  public TransactionReport data(List<TransactionReportRow> data) {
    this.data = data;
    return this;
  }

  public TransactionReport addDataItem(TransactionReportRow dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<TransactionReportRow>();
    }
    this.data.add(dataItem);
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @Schema(description = "")
  public List<TransactionReportRow> getData() {
    return data;
  }

  public void setData(List<TransactionReportRow> data) {
    this.data = data;
  }

  public TransactionReport totalRecords(Integer totalRecords) {
    this.totalRecords = totalRecords;
    return this;
  }

   /**
   * Get totalRecords
   * @return totalRecords
  **/
  @Schema(description = "")
  public Integer getTotalRecords() {
    return totalRecords;
  }

  public void setTotalRecords(Integer totalRecords) {
    this.totalRecords = totalRecords;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionReport transactionReport = (TransactionReport) o;
    return Objects.equals(this.errorCode, transactionReport.errorCode) &&
        Objects.equals(this.data, transactionReport.data) &&
        Objects.equals(this.totalRecords, transactionReport.totalRecords);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errorCode, data, totalRecords);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionReport {\n");
    
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    totalRecords: ").append(toIndentedString(totalRecords)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public void writeToParcel(Parcel out, int flags) {
    out.writeValue(errorCode);
    out.writeValue(data);
    out.writeValue(totalRecords);
  }

  TransactionReport(Parcel in) {
    errorCode = (Integer)in.readValue(null);
    data = (List<TransactionReportRow>)in.readValue(TransactionReportRow.class.getClassLoader());
    totalRecords = (Integer)in.readValue(null);
  }

  public int describeContents() {
    return 0;
  }

  public static final Parcelable.Creator<TransactionReport> CREATOR = new Parcelable.Creator<TransactionReport>() {
    public TransactionReport createFromParcel(Parcel in) {
      return new TransactionReport(in);
    }
    public TransactionReport[] newArray(int size) {
      return new TransactionReport[size];
    }
  };
}
