/*
 * bnm
 * Books N More's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: samarthr1@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package in.co.booksnmore.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
import android.os.Parcelable;
import android.os.Parcel;
/**
 * TransactionReportRow
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-09-01T11:17:49.897Z[GMT]")
public class TransactionReportRow implements Parcelable {
  @SerializedName("amount")
  private Integer amount = null;

  @SerializedName("author")
  private String author = null;

  @SerializedName("memberId")
  private String memberId = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("title")
  private String title = null;

  @SerializedName("transDate")
  private String transDate = null;

  @SerializedName("transId")
  private BigDecimal transId = null;

  @SerializedName("transType")
  private String transType = null;

  @SerializedName("bookId")
  private String bookId = null;

  public TransactionReportRow() {
  }
  public TransactionReportRow amount(Integer amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @Schema(description = "")
  public Integer getAmount() {
    return amount;
  }

  public void setAmount(Integer amount) {
    this.amount = amount;
  }

  public TransactionReportRow author(String author) {
    this.author = author;
    return this;
  }

   /**
   * Get author
   * @return author
  **/
  @Schema(description = "")
  public String getAuthor() {
    return author;
  }

  public void setAuthor(String author) {
    this.author = author;
  }

  public TransactionReportRow memberId(String memberId) {
    this.memberId = memberId;
    return this;
  }

   /**
   * Get memberId
   * @return memberId
  **/
  @Schema(description = "")
  public String getMemberId() {
    return memberId;
  }

  public void setMemberId(String memberId) {
    this.memberId = memberId;
  }

  public TransactionReportRow name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public TransactionReportRow title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @Schema(description = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public TransactionReportRow transDate(String transDate) {
    this.transDate = transDate;
    return this;
  }

   /**
   * Get transDate
   * @return transDate
  **/
  @Schema(description = "")
  public String getTransDate() {
    return transDate;
  }

  public void setTransDate(String transDate) {
    this.transDate = transDate;
  }

  public TransactionReportRow transId(BigDecimal transId) {
    this.transId = transId;
    return this;
  }

   /**
   * Get transId
   * @return transId
  **/
  @Schema(description = "")
  public BigDecimal getTransId() {
    return transId;
  }

  public void setTransId(BigDecimal transId) {
    this.transId = transId;
  }

  public TransactionReportRow transType(String transType) {
    this.transType = transType;
    return this;
  }

   /**
   * Get transType
   * @return transType
  **/
  @Schema(description = "")
  public String getTransType() {
    return transType;
  }

  public void setTransType(String transType) {
    this.transType = transType;
  }

  public TransactionReportRow bookId(String bookId) {
    this.bookId = bookId;
    return this;
  }

   /**
   * Get bookId
   * @return bookId
  **/
  @Schema(description = "")
  public String getBookId() {
    return bookId;
  }

  public void setBookId(String bookId) {
    this.bookId = bookId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionReportRow transactionReportRow = (TransactionReportRow) o;
    return Objects.equals(this.amount, transactionReportRow.amount) &&
        Objects.equals(this.author, transactionReportRow.author) &&
        Objects.equals(this.memberId, transactionReportRow.memberId) &&
        Objects.equals(this.name, transactionReportRow.name) &&
        Objects.equals(this.title, transactionReportRow.title) &&
        Objects.equals(this.transDate, transactionReportRow.transDate) &&
        Objects.equals(this.transId, transactionReportRow.transId) &&
        Objects.equals(this.transType, transactionReportRow.transType) &&
        Objects.equals(this.bookId, transactionReportRow.bookId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amount, author, memberId, name, title, transDate, transId, transType, bookId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionReportRow {\n");
    
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    author: ").append(toIndentedString(author)).append("\n");
    sb.append("    memberId: ").append(toIndentedString(memberId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    transDate: ").append(toIndentedString(transDate)).append("\n");
    sb.append("    transId: ").append(toIndentedString(transId)).append("\n");
    sb.append("    transType: ").append(toIndentedString(transType)).append("\n");
    sb.append("    bookId: ").append(toIndentedString(bookId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public void writeToParcel(Parcel out, int flags) {
    out.writeValue(amount);
    out.writeValue(author);
    out.writeValue(memberId);
    out.writeValue(name);
    out.writeValue(title);
    out.writeValue(transDate);
    out.writeValue(transId);
    out.writeValue(transType);
    out.writeValue(bookId);
  }

  TransactionReportRow(Parcel in) {
    amount = (Integer)in.readValue(null);
    author = (String)in.readValue(null);
    memberId = (String)in.readValue(null);
    name = (String)in.readValue(null);
    title = (String)in.readValue(null);
    transDate = (String)in.readValue(null);
    transId = (BigDecimal)in.readValue(BigDecimal.class.getClassLoader());
    transType = (String)in.readValue(null);
    bookId = (String)in.readValue(null);
  }

  public int describeContents() {
    return 0;
  }

  public static final Parcelable.Creator<TransactionReportRow> CREATOR = new Parcelable.Creator<TransactionReportRow>() {
    public TransactionReportRow createFromParcel(Parcel in) {
      return new TransactionReportRow(in);
    }
    public TransactionReportRow[] newArray(int size) {
      return new TransactionReportRow[size];
    }
  };
}
